ShopTARge23/ShopTARge23/Models/OpenWeathers/OpenWeatherSearchViewModel.cs
namespace ShopTARge23.Models.OpenWeathers
{
    public class OpenWeatherSearchViewModel
    {
        public string CityName { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/OpenWeathers/OpenWeatherViewModel.cs
namespace ShopTARge23.Models.OpenWeathers
{
    public class OpenWeatherViewModel
    {
        public string CityName { get; set; }
        public double Temperature { get; set; }
        public string Description { get; set; }
        public string WeatherMain { get; set; }
        public double FeelsLike { get; set; }
        public double TempMin { get; set; }
        public double TempMax { get; set; }
        public int Humidity { get; set; }
        public int Pressure { get; set; }
        public double WindSpeed { get; set; }
        public int WindDeg { get; set; }
        public int Cloudiness { get; set; }
        public string Icon { get; set; }
    }
}

ShopTARge23/ShopTARge23/Controllers/OpenWeathersController.cs
using Microsoft.AspNetCore.Mvc;
using ShopTARge23.Core.Dto.WeatherDtos.OpenWeatherDtos;
using ShopTARge23.Core.ServiceInterface;
using ShopTARge23.Models.OpenWeathers;

namespace ShopTARge23.Controllers
{
    public class OpenWeathersController : Controller
    {
        private readonly IOpenWeatherServices _openWeatherServices;

        public OpenWeathersController(IOpenWeatherServices openWeatherServices)
        {
            _openWeatherServices = openWeatherServices;
        }

        public IActionResult Index()
        {
            var vm = new OpenWeatherSearchViewModel();
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> SearchCity(OpenWeatherSearchViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var dto = new OpenWeatherResultDto()
                {
                    CityName = vm.CityName
                };

                var result = await _openWeatherServices.GetOpenWeatherResult(dto);

                var weatherVm = new OpenWeatherViewModel()
                {
                    CityName = result.CityName,
                    Temperature = result.Temperature,
                    Description = result.Description,
                    WeatherMain = result.WeatherMain,
                    FeelsLike = result.FeelsLike,
                    TempMin = result.TempMin,
                    TempMax = result.TempMax,
                    Humidity = result.Humidity,
                    Pressure = result.Pressure,
                    WindSpeed = result.WindSpeed,
                    WindDeg = result.WindDeg,
                    Cloudiness = result.Cloudiness,
                    Icon = result.Icon
                };

                return RedirectToAction("City", weatherVm);
            }

            return View("Index", vm);
        }

        public IActionResult City(OpenWeatherViewModel vm)
        {
            return View(vm);
        }
    }
}

ShopTARge23/ShopTARge23/Views/OpenWeathers/City.cshtml
@model ShopTARge23.Models.OpenWeathers.OpenWeatherViewModel

<div class="container">
    <h2>Weather for @Html.DisplayFor(model => model.CityName)</h2>
    <hr />
    <dl class="row text-dark">
        <div class="form-group row">
            <label asp-for="Temperature" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Temperature) °C
        </div>

        <div class="form-group row">
            <label asp-for="Description" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Description)
        </div>

        <div class="form-group row">
            <label asp-for="WeatherMain" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.WeatherMain)
        </div>

        <div class="form-group row">
            <label asp-for="FeelsLike" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.FeelsLike) °C
        </div>

        <div class="form-group row">
            <label asp-for="TempMin" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.TempMin) °C
        </div>

        <div class="form-group row">
            <label asp-for="TempMax" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.TempMax) °C
        </div>

        <div class="form-group row">
            <label asp-for="Humidity" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Humidity) %
        </div>

        <div class="form-group row">
            <label asp-for="Pressure" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Pressure) hPa
        </div>

        <div class="form-group row">
            <label asp-for="WindSpeed" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.WindSpeed) m/s
        </div>

        <div class="form-group row">
            <label asp-for="Cloudiness" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Cloudiness) %
        </div>
    </dl>
</div>

<div class="container">
    <form method="get">
        <button asp-controller="OpenWeathers" asp-action="Index" class="btn btn-success">Back to Search</button>
    </form>
</div>

ShopTARge23/ShopTARge23/Views/OpenWeathers/Index.cshtml
@model ShopTARge23.Models.OpenWeathers.OpenWeatherSearchViewModel

<h1>Search City Weather</h1>

<div class="container">
    <form method="post">
        <div class="container">
            <div class="form-group col-md-offset-3 col-md-5">
                <h2>Search the weather in a city</h2>
                <label asp-for="CityName" style="font-family: Arial"></label>
                <input asp-for="CityName" class="form-control" />
                <span asp-validation-for="CityName" class="text-danger"></span>
            </div>
        </div>
        <div class="container">
            <div class="form-group col-md-offset-3 col-md-5">
                <button asp-controller="OpenWeathers" asp-action="searchCity" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
</div>