ShopTARge23/ShopTARge23/Models/Spaceships/ImageViewModel.cs
namespace ShopTARge23.Models.Spaceships
{
    public class ImageViewModel
    {
        public Guid ImageId { get; set; }
        public string FilePath { get; set; }
        public Guid SpaceshipId { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/Spaceships/SpaceshipCreateUpdateViewModel.cs
namespace ShopTARge23.Models.Spaceships
{
    public class SpaceshipCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Typename { get; set; }
        public string SpaceshipModel { get; set; }
        public DateTime BuiltDate { get; set; }
        public int Crew { get; set; }
        public int EnginePower { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<SpaceshipImageViewModel> Image { get; set; }
            = new List<SpaceshipImageViewModel>();


        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/Spaceships/SpaceshipDeleteViewModel.cs
namespace ShopTARge23.Models.Spaceships
{
    public class SpaceshipDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Typename { get; set; }
        public string SpaceshipModel { get; set; }
        public DateTime BuiltDate { get; set; }
        public int Crew { get; set; }
        public int EnginePower { get; set; }


        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/Spaceships/SpaceshipDetailsViewModel.cs
namespace ShopTARge23.Models.Spaceships
{
    public class SpaceshipDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Typename { get; set; }
        public string SpaceshipModel { get; set; }
        public DateTime BuiltDate { get; set; }
        public int Crew { get; set; }
        public int EnginePower { get; set; }


        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/Spaceships/SpaceshipImageViewModel.cs
namespace ShopTARge23.Models.Spaceships
{
    public class SpaceshipImageViewModel
    {
        public Guid ImageId { get; set; }
        public string FilePath { get; set; }
        public Guid SpaceshipId { get; set; }
    }
}

ShopTARge23/ShopTARge23/Models/Spaceships/SpaceshipsIndexViewModel.cs
namespace ShopTARge23.Models.Spaceships
{
    public class SpaceshipsIndexViewModel
    {
        public Guid? Id { get; set; }
        public string Name { get; set; }
        public string Typename { get; set; }
        public string SpaceshipModel { get; set; }
        public DateTime BuiltDate { get; set; }
        public int Crew { get; set; }
        public int EnginePower { get; set; }
    }
}

ShopTARge23/ShopTARge23/Controllers/SpaceshipsController.cs
using Microsoft.AspNetCore.Mvc;
using ShopTARge23.Core.Dto;
using ShopTARge23.Core.ServiceInterface;
using ShopTARge23.Data;
using ShopTARge23.Models.Spaceships;

namespace ShopTARge23.Controllers
{
    public class SpaceshipsController : Controller
    {
        private readonly ShopTARge23Context _context;
        private readonly ISpaceshipsServices _spaceshipServices;

        public SpaceshipsController
            (
                ShopTARge23Context context,
                ISpaceshipsServices spaceshipsServices
            )
        {
            _context = context;
            _spaceshipServices = spaceshipsServices;
        }


        public IActionResult Index()
        {
            var result = _context.Spaceships
                .Select(x => new SpaceshipsIndexViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    Typename = x.Typename,
                    BuiltDate = x.BuiltDate,
                    Crew = x.Crew,
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            SpaceshipCreateUpdateViewModel result = new();

            return View("CreateUpdate", result);
        }

        [HttpPost]
        public async Task<IActionResult> Create(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Typename = vm.Typename,
                SpaceshipModel = vm.SpaceshipModel,
                BuiltDate = vm.BuiltDate,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                FileToApiDtos = vm.Image
                    .Select(x => new FileToApiDto
                    {
                        Id = x.ImageId,
                        ExistingFilePath = x.FilePath,
                        SpaceshipId = x.SpaceshipId
                    }).ToArray()
            };

            var result = await _spaceshipServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailAsync(id);

            if (spaceship == null)
            {
                return View("Error");
            }

            var vm = new SpaceshipDetailsViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Typename = spaceship.Typename;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.SpaceshipModel = spaceship.SpaceshipModel;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;


            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var vm = new SpaceshipCreateUpdateViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Typename = spaceship.Typename;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.SpaceshipModel = spaceship.SpaceshipModel;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Typename = vm.Typename,
                SpaceshipModel = vm.SpaceshipModel,
                BuiltDate = vm.BuiltDate,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt
            };

            var result = await _spaceshipServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var vm = new SpaceshipDeleteViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Typename = spaceship.Typename;
            vm.BuiltDate = spaceship.BuiltDate;
            vm.SpaceshipModel = spaceship.SpaceshipModel;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var spaceship = await _spaceshipServices.Delete(id);

            if (spaceship == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopTARge23/ShopTARge23/Views/Spaceships/CreateUpdate.cshtml
@model ShopTARge23.Models.Spaceships.SpaceshipCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Typename" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Typename" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="SpaceshipModel" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="SpaceshipModel" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuiltDate" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Crew" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnginePower" class="form-control" />
            </div>
        </div>



        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="spaceships" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="spaceships" type="submit" class="btn btn-primary" value="Create" />
        }


    </form>
</div>

ShopTARge23/ShopTARge23/Views/Spaceships/Delete.cshtml
@model ShopTARge23.Models.Spaceships.SpaceshipDeleteViewModel

<h1>Delete</h1>

<div>
    <h4>Spaceships</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Name)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Typename" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Typename)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="SpaceshipModel" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.SpaceshipModel)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuiltDate)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Crew)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.EnginePower)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
    </dl>

    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" asp-controller="spaceships" class="btn btn-success">Back</a>
    </form>
</div>

ShopTARge23/ShopTARge23/Views/Spaceships/Details.cshtml
@model ShopTARge23.Models.Spaceships.SpaceshipDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Spaceships</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="form-group row">
            <label asp-for="Typename" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Typename)
        </div>

        <div class="form-group row">
            <label asp-for="SpaceshipModel" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.SpaceshipModel)
        </div>

        <div class="form-group row">
            <label asp-for="BuiltDate" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuiltDate)
        </div>

        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Crew)
        </div>

        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.EnginePower)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
    </dl>

    <a asp-action="Index" asp-controller="spaceships" class="btn btn-danger">Back</a>
</div>

ShopTARge23/ShopTARge23/Views/Spaceships/Index.cshtml
@model IEnumerable<ShopTARge23.Models.Spaceships.SpaceshipsIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="Spaceships" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
    Spaceships
</div>
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Built date</th>
                <th scope="col">Crew</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var spaceships in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@spaceships.Name</td>
                    <td>@spaceships.Typename</td>
                    <td>@spaceships.BuiltDate</td>
                    <td>@spaceships.Crew</td>
                    <td>
                        <a asp-action="details" asp-controller="spaceships" asp-route-id="@spaceships.Id" class="btn btn-info">Details</a>
                        <a asp-action="update" asp-controller="spaceships" asp-route-id="@spaceships.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="spaceships" asp-route-id="@spaceships.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

                rowNumber += 1;
            }
        </tbody>
    </table>
</form>

ShopTARge23/ShopTARge23/Views/Spaceships/_Images.cshtml
@model ShopTARge23.Models.Spaceships.SpaceshipImageViewModel

@{
    var photoPaths = "~/multipleFileUpload/" + (Model.FilePath ?? "noimage.jpg");
}

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.FilePath</div>
    <img class="card-img-top" src="@photoPaths" asp-append-version="true" />
</div>